plugins {
    id 'java'
    id 'war'
    id 'maven-publish'
    id "org.hidetake.ssh" version "2.11.2"
}

group = 'com.example'
version = '1.0-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    // Gson
    implementation 'com.google.code.gson:gson:2.10'

    // Servlet (Tomcat 10+)
    providedCompile 'jakarta.servlet:jakarta.servlet-api:6.1.0'

    // JDBI
    implementation 'org.jdbi:jdbi3-core:3.50.0'

    // MySQL
    implementation 'com.mysql:mysql-connector-j:9.5.0'

    // JSTL API
    implementation 'jakarta.servlet.jsp.jstl:jakarta.servlet.jsp.jstl-api:3.0.0'

    // JSTL Implementation
    implementation 'org.glassfish.web:jakarta.servlet.jsp.jstl:3.0.1'

    // JetBrains annotations
    implementation 'org.jetbrains:annotations:24.1.0'

    // Jakarta Mail
    implementation 'org.eclipse.angus:jakarta.mail:2.0.3'

    // JUnit 5
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.13.2'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.13.2'
}

tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'
}

test {
    useJUnitPlatform()
}

// ==========================================
// CẤU HÌNH DEPLOY LÊN SERVER BẰNG SSH
// ==========================================
apply plugin: 'org.hidetake.ssh'

remotes {
    host {
        // Sửa IP và user lại cho khớp với MobaXterm
        host = '192.168.124.128'
        user = 'ubuntu'
        password = '1'
    }
}

ssh.settings {
    knownHosts = allowAnyHosts
}

task docker_app_start {
    doLast {
        println '--- Đang khởi động Tomcat ---'
        ssh.run {
            session(remotes.host) {
                // Xóa container cũ (không cần sudo)
                execute 'docker rm -f tomcat10', ignoreError: true

                // Chạy lệnh run (bỏ sudo, bỏ -it)
                execute 'docker run -d ' +
                        '--name tomcat10 ' +
                        '--restart always ' +
                        '-v /usr/deploy:/usr/local/tomcat/webapps ' +
                        '-p 80:8080 ' +
                        'tomcat:10.1'

                println '--- Deploy thành công lên cổng 80! ---'
            }
        }
    }
}

task docker_upload_file_to_server {
    doLast {
        ssh.run {
            session(remotes.host) {
                execute 'rm -f /usr/deploy/ROOT.war', ignoreError: true
                execute 'rm -rf /usr/deploy/ROOT/', ignoreError: true

                put from: tasks.war.archiveFile.get().asFile.path,
                        into: "/usr/deploy/ROOT.war" // Đổi tên thành ROOT
            }
        }
    }
}

task docker_deploy {
    dependsOn build
    dependsOn docker_upload_file_to_server
    dependsOn docker_app_start
    tasks.getByName('docker_app_start').mustRunAfter docker_upload_file_to_server
}